### ISSUE TITLE
ReferenceError: TextEncoder is not defined

### ISSUE THREAD

**Issue by rapidgithub** [altsam/create_an_airdrop_program#6]
Does not work with **nodejs 10.x**
```
ReferenceError: TextEncoder is not defined
    at Function.fromSecretKey (/home/web3js/node_modules/@solana/web3.js/lib/index.cjs.js:7320:23)
    at getWalletBalance (/home/web3js/index.js:26:31)
    at driverFunction (/home/web3js/index.js:55:11)
    at Object.<anonymous> (/home/web3js/index.js:59:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
```
Need to add below in `index.js`
`global.TextEncoder = require("util").TextEncoder;`

**Comment by Tushar7-pixel** [comment]
i am Having Same Issue...!  Did you find any  alternate solution yet??

**Comment by yaseenammaar** [comment]
Same Issue here, any fix?

**Comment by Tushar7-pixel** [comment]
> Same Issue here, any fix?

Yes, I have installed WSL command-line interface and it worked...! but i had to install nodeJS, rust and solana again in this cli..! which was frustrating...! "Best of Luck"
